Repository dev-launchers/dev-launchers-platform, pull requests merged in 2023-01, with the labels that each got.

#781 User Card organism
  packages/UI/src/assets/images/test-image.png
  packages/UI/src/components/organisms/UserCard/UserCard.stories.tsx
  packages/UI/src/components/organisms/UserCard/UserCard.tsx
  packages/UI/src/components/organisms/UserCard/index.tsx
Labels: Platform Enablement

#791 Anouar/Cookies
  apps/app/next.config.js
  apps/app/package.json
  apps/app/pages/_app.js
  apps/app/pages/scripts/iubendaScript.js
  yarn.lock
Labels: IdeaSpace

#792 development/components fix
  apps/dev-recruiters/src/components/modules/FormPage/signUpForm.tsx
  packages/UI/src/components/organisms/Navigation/MobileNavigation.tsx
  packages/UI/src/components/organisms/Navigation/Navigation.tsx
  packages/UI/src/components/organisms/Navigation/Styled.Navigation.ts
  packages/UI/src/utils/Logout.js
  packages/UI/src/utils/formErrorScroller.tsx
Labels: FRONTEND, Platform Enablement
